# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED'), (4, 'EXPIRED')], default=0),
        ),
    ]
