# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180715_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_activity_id', models.IntegerField()),
                ('answer_group_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('answer_source', models.CharField(blank=True, max_length=500, null=True)),
                ('answer_value', models.IntegerField()),
                ('choce_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('weight_value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAnswers'),
        ),
    ]
